/// @description Create
menuX = x;
menuY = y;
buttonHeight = 16;
button[0] = "Start";
button[1] = "Fullscreen";
button[2] = "Tutorial";
button[3] = "Quit";
buttonCount = array_length_1d(button);
menuIndex = 0;
lastSelected = 0;
lastAxis0Value = 0;
lastAxis4Value = 0;